// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace S0WISRXX.PurchaseOrder.Repository.Models;

public partial class PoextendedMessageDetailStg : BaseModel
{
    public int Id { get; set; }

    public int PoextendedMessageHeaderId { get; set; }

    public string RecordType { get; set; }

    public string ActionCode { get; set; }

    public string Ponumber { get; set; }

    public string MessageNumber { get; set; }

    public string LineNumber { get; set; }

    public string MessageDescription { get; set; }

    public string CorrelationId { get; set; }

    public string MessageId { get; set; }

    public DateTime? PutDateTime { get; set; }

    public string LastUpdatedBy { get; set; }
}