// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace S0WISRXX.PurchaseOrder.Repository.Models;

public partial class PoextendedMessageHeaderStg : BaseModel
{
    public int Id { get; set; }

    public int PostatusId { get; set; }

    public string RecordType { get; set; }

    public string ActionCode { get; set; }

    public string DistributionCenterId { get; set; }

    public string ShipToWarehouse { get; set; }

    public string Ponumber { get; set; }

    public string MessageNumber { get; set; }

    public string ChangedDate1 { get; set; }

    public string ChangedOperator1 { get; set; }

    public string ChangedDate2 { get; set; }

    public string ChangedOperator2 { get; set; }

    public string ChangedDate3 { get; set; }

    public string ChangedOperator3 { get; set; }

    public string CorrelationId { get; set; }

    public string MessageId { get; set; }

    public DateTime? PutDateTime { get; set; }

    public string LastUpdatedBy { get; set; }

    public virtual Status Postatus { get; set; }

    public bool? IsSkipped { get; set; }
}