// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace S0WISRXX.PurchaseOrder.Repository.Models;

public partial class PurchaseOrderMessageDetail : BaseModel
{
    public int Id { get; set; }

    public int PurchaseOrderMessageId { get; set; }

    public int PurchaseOrderId { get; set; }
    [NotMapped]
    public int PONumber { get; set; }
    public string ActionCode { get; set; }

    public string MessageNumber { get; set; }

    public string LineNumber { get; set; }

    public string MessageDescription { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public virtual PurchaseOrder3 PurchaseOrder { get; set; }

    public virtual PurchaseOrderMessage PurchaseOrderMessage { get; set; }
}